[package]
name = "rust99problems"
version = "0.1.0"
authors = ["Checkmate50 <dgeisler50@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
